#!/bin/bash
icon='󰂲'
class=""

#stamp bluetooth device name or empty string
device=$(bluetoothctl info | grep "Name" | cut -d " " -f 2-)

#device name is empty, no device connected
if [ -z "$device" ]; then
    device="vuoto"
fi

#if the bluetooth is on, turn it off
if [ $(bluetoothctl show | grep "Powered: yes" | wc -l) -eq 1 ]; then
    icon=''
    class="on"

#if the bluetooth is off, turn it on
else
    icon='󰂲'
    class="off"
fi

#use jq to format output
echo $icon $class $device | jq -R -s 'split(" ") | {icon: .[0], class: .[1], device: .[2]}'