#!/bin/bash

currentTheme=`cat ~/.config/eww/consts/theme.txt`

hyprConfig=~/.config/hypr
neoConfig=~/.config/neofetch

themes=`ls ~/.config/eww/themes`
themes=($themes)

themeName=""
themePath=""

# select the next theme in the list or the first one if the current theme is the last one
for i in "${!themes[@]}"; do
    if [[ "${themes[$i]}" = "${currentTheme}" ]]; then
        if [[ "${themes[$i+1]}" = "" ]]; then
            themeName=${themes[0]}
        else
            themeName=${themes[$i+1]}
        fi
    fi
done

themePath=~/.config/eww/themes/$themeName

echo $themeName > ~/.config/eww/consts/theme.txt

rm ~/.config/eww/scss/main.scss
ln -s $themePath/main.scss ~/.config/eww/scss/main.scss
cp $themePath/background.jpg $hyprConfig/background.jpg
cp $themePath/hypr-colors.conf $hyprConfig/hypr-colors.conf
cp $themePath/terminal_image.jpg $neoConfig/terminal_image.jpg

wal -i $themePath/background.jpg &

# if hyprpaper is running kill it
if pgrep -x "hyprpaper" > /dev/null
then
    killall hyprpaper
fi

# start hyprpaper
hyprpaper &

sleep 1

eww reload